{{- if .Values.backend.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "penpot.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "penpot.labels" . | nindent 4 }}
spec:
  {{- if .Values.backend.pdb.minAvailable }}
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
  {{- else if .Values.backend.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.backend.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: 0
  {{- end }}
  selector:
    matchLabels:
      app: penpot-backend
{{- end -}}
